import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import {
  FileTextIcon,
  DownloadIcon,
  EyeIcon,
  SearchIcon,
  FilterIcon,
  SortAscIcon,
  PlusIcon,
  RefreshCwIcon,
  TrendingUpIcon,
  CalendarIcon,
  MapPinIcon,
  CheckCircleIcon,
  AlertTriangleIcon,
  XCircleIcon,
  LoaderIcon,
} from 'lucide-react';
import MainLayout from '../layouts/MainLayout';
import Card from '../components/ui/Card';
import Button from '../components/ui/Button';
import { useTranslation } from 'react-i18next';
import jsPDF from 'jspdf';

interface Report {
  id: string;
  name: string;
  date: string;
  location: string;
  status: 'suitable' | 'conditional' | 'unsuitable';
  harvestPotential: number;
}

type StatusFilter = 'all' | Report['status'];
type SortOption = 'newest' | 'oldest' | 'potential';

const Reports: React.FC = () => {
  const { t } = useTranslation();
  const navigate = useNavigate();

  const [reports, setReports] = useState<Report[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [searchTerm, setSearchTerm] = useState('');
  const [statusFilter, setStatusFilter] = useState<StatusFilter>('all');
  const [sortOption, setSortOption] = useState<SortOption>('newest');
  const [downloadingPdf, setDownloadingPdf] = useState<string | null>(null);

  // PDF Download functionality
  const downloadReportAsPDF = async (report: Report) => {
    setDownloadingPdf(report.id);
    
    try {
      const token = localStorage.getItem('token');
      if (!token) {
        throw new Error('Please sign in to download reports.');
      }

      // Fetch full report data
      const response = await fetch(`/api/assessments/${report.id}`, {
        headers: {
          'Content-Type': 'application/json',
          Authorization: `Bearer ${token}`,
        },
      });

      if (!response.ok) {
        throw new Error('Failed to fetch report details.');
      }

      const reportData = await response.json();

      // Create PDF content
      const pdf = new jsPDF();
      const pageWidth = pdf.internal.pageSize.getWidth();
      const margin = 20;
      let yPosition = margin;

      // Helper function to add text with word wrap
      const addText = (text: string, fontSize = 12, isBold = false) => {
        pdf.setFontSize(fontSize);
        if (isBold) {
          pdf.setFont('helvetica', 'bold');
        } else {
          pdf.setFont('helvetica', 'normal');
        }
        
        const lines = pdf.splitTextToSize(text, pageWidth - 2 * margin);
        pdf.text(lines, margin, yPosition);
        yPosition += (fontSize * 0.75 * lines.length) + 10;
        
        if (yPosition > pdf.internal.pageSize.getHeight() - margin) {
          pdf.addPage();
          yPosition = margin;
        }
      };

      // PDF Header
      pdf.setFillColor(59, 130, 246); // Blue background
      pdf.rect(0, 0, pageWidth, 40, 'F');
      
      pdf.setTextColor(255, 255, 255);
      pdf.setFontSize(24);
      pdf.setFont('helvetica', 'bold');
      pdf.text('RainWise Assessment Report', margin, 25);
      
      yPosition = 60;
      pdf.setTextColor(0, 0, 0);

      // Report Details
      addText(`Report: ${report.name}`, 18, true);
      addText(`Date: ${formatDate(report.date)}`, 12);
      addText(`Location: ${report.location || 'Not specified'}`, 12);
      addText(`Status: ${getStatusText(report.status)}`, 12, true);
      addText(`Harvest Potential: ${formatHarvestPotential(report.harvestPotential)}`, 12, true);

      yPosition += 10;
      
      // Assessment Details
      if (reportData) {
        addText('Assessment Details', 16, true);
        addText(`Name: ${reportData.name || 'N/A'}`, 12);
        addText(`Number of Dwellers: ${reportData.dwellers || 'N/A'}`, 12);
        addText(`Phone: ${reportData.phone || 'N/A'}`, 12);
        addText(`Email: ${reportData.email || 'N/A'}`, 12);
        addText(`Roof Area: ${reportData.roofArea || 'N/A'} sq ft`, 12);
        addText(`Open Space: ${reportData.openSpace || 'N/A'} sq ft`, 12);
        addText(`Roof Type: ${reportData.roofType || 'N/A'}`, 12);
        addText(`Soil Type: ${reportData.soilType || 'N/A'}`, 12);
        addText(`Annual Rainfall: ${reportData.rainfall || 'N/A'} mm`, 12);
        
        if (reportData.latitude && reportData.longitude) {
          addText(`Coordinates: ${reportData.latitude}, ${reportData.longitude}`, 12);
        }
      }

      yPosition += 10;
      addText('Generated by RainWise - Rainwater Harvesting Assessment Tool', 10);
      addText(`Generated on: ${new Date().toLocaleDateString()}`, 10);

      // Save PDF
      const fileName = `RainWise_Report_${report.name.replace(/[^a-zA-Z0-9]/g, '_')}_${new Date().toISOString().split('T')[0]}.pdf`;
      pdf.save(fileName);
      
    } catch (error) {
      console.error('Error generating PDF:', error);
      alert('Failed to download PDF. Please try again.');
    } finally {
      setDownloadingPdf(null);
    }
  };

  const getStatusText = (status: Report['status']) => {
    switch (status) {
      case 'suitable':
        return 'Highly Suitable';
      case 'conditional':
        return 'Conditionally Suitable';
      case 'unsuitable':
        return 'Not Recommended';
    }
  };

  const deriveStatus = (value?: string): Report['status'] => {
    const normalized = (value ?? '').toLowerCase();
    if (normalized.includes('unsuitable') || normalized.includes('not')) {
      return 'unsuitable';
    }
    if (
      normalized.includes('suitable') ||
      normalized.includes('high') ||
      normalized.includes('recommended')
    ) {
      return 'suitable';
    }
    return 'conditional';
  };

  const loadReports = useCallback(async () => {
    setLoading(true);
    setError(null);

    try {
      const token = localStorage.getItem('token');
      if (!token) {
        throw new Error('Please sign in to view your reports.');
      }

      const response = await fetch('/api/assessments', {
        headers: {
          'Content-Type': 'application/json',
          Authorization: `Bearer ${token}`,
        },
      });

      if (!response.ok) {
        const detail = await response.text();
        throw new Error(detail || 'Failed to load assessments.');
      }

      const payload = await response.json();
      const list = Array.isArray(payload) ? payload : [payload];

      const normalized = list.map((item: Record<string, unknown>, index: number): Report => {
        const createdAt =
          (item.createdAt as string) || (item.updatedAt as string) || (item.date as string) || new Date().toISOString();
        const potential =
          (item.potentialHarvest as number) ??
          (item.potential_harvest as number) ??
          (item.harvestPotential as number) ??
          (item.harvest_potential as number) ??
          0;

        const harvestValue =
          typeof potential === 'string' ? parseFloat(potential) : Number(potential);

        return {
          id: (item._id as string) ?? (item.id as string) ?? `${index}`,
          name: (item.name as string) || t('Assessment Report'),
          date: createdAt,
          location: (item.address as string) || (item.location as string) || '',
          status: deriveStatus((item.status as string) ?? (item.feasibility as string)),
          harvestPotential: Number.isFinite(harvestValue) ? harvestValue : 0,
        };
      });

      setReports(normalized);
    } catch (err) {
      const message =
        err instanceof Error ? err.message : 'Unable to load reports.';
      setError(message);
      setReports([]);
    } finally {
      setLoading(false);
    }
  }, [t]);

  useEffect(() => {
    loadReports();
  }, [loadReports]);

  const filteredReports = useMemo(() => {
    const query = searchTerm.trim().toLowerCase();

    const filtered = reports.filter((report) => {
      const matchesSearch =
        !query ||
        report.name.toLowerCase().includes(query) ||
        report.location.toLowerCase().includes(query);
      const matchesStatus =
        statusFilter === 'all' || report.status === statusFilter;

      return matchesSearch && matchesStatus;
    });

    return filtered.sort((a, b) => {
      if (sortOption === 'newest') {
        return new Date(b.date).getTime() - new Date(a.date).getTime();
      }
      if (sortOption === 'oldest') {
        return new Date(a.date).getTime() - new Date(b.date).getTime();
      }
      return (b.harvestPotential || 0) - (a.harvestPotential || 0);
    });
  }, [reports, searchTerm, statusFilter, sortOption]);

  const getStatusBadge = (status: Report['status']) => {
    switch (status) {
      case 'suitable':
        return (
          <span className="bg-gradient-to-r from-green-100 to-emerald-100 text-green-800 text-sm px-3 py-1 rounded-full font-semibold border border-green-200">
            {t('Highly Suitable')}
          </span>
        );
      case 'conditional':
        return (
          <span className="bg-gradient-to-r from-yellow-100 to-amber-100 text-yellow-800 text-sm px-3 py-1 rounded-full font-semibold border border-yellow-200">
            {t('Conditionally Suitable')}
          </span>
        );
      case 'unsuitable':
        return (
          <span className="bg-gradient-to-r from-red-100 to-rose-100 text-red-800 text-sm px-3 py-1 rounded-full font-semibold border border-red-200">
            {t('Not Recommended')}
          </span>
        );
    }
  };

  const formatHarvestPotential = (value: number) => {
    if (!value) {
      return 'N/A';
    }
    if (value >= 1_000_000) {
      return `${(value / 1_000_000).toFixed(1)}M L/year`;
    }
    if (value >= 1_000) {
      return `${(value / 1_000).toFixed(1)}K L/year`;
    }
    return `${value.toLocaleString()} L/year`;
  };

  const formatDate = (value: string) => {
    const parsed = new Date(value);
    return Number.isNaN(parsed.getTime())
      ? value
      : parsed.toLocaleDateString(undefined, {
          year: 'numeric',
          month: 'short',
          day: 'numeric',
        });
  };

  return (
    <MainLayout>
      {/* Enhanced Header Section */}
      <div className="relative mb-8 -mx-6 -mt-6 px-6 pt-8 pb-6 bg-gradient-to-r from-blue-50 via-indigo-50 to-purple-50 border-b border-blue-100">
        <div className="absolute inset-0 bg-grid-pattern opacity-5"></div>
        <div className="relative">
          <div className="flex flex-col lg:flex-row items-start lg:items-center justify-between gap-6">
            <div className="flex items-center space-x-4">
              <div className="w-14 h-14 bg-gradient-to-br from-blue-500 to-indigo-600 rounded-2xl flex items-center justify-center shadow-xl">
                <FileTextIcon className="h-7 w-7 text-white" />
              </div>
              <div>
                <h1 className="text-4xl font-bold bg-gradient-to-r from-blue-600 via-indigo-600 to-purple-600 bg-clip-text text-transparent mb-2">
                  {t('Assessment Reports')}
                </h1>
                <p className="text-indigo-700 font-medium text-lg">
                  {t('View and manage your past assessments')}
                </p>
              </div>
            </div>
            
            <div className="flex items-center space-x-4">
              <div className="flex items-center space-x-2 px-4 py-2 bg-white bg-opacity-70 rounded-full backdrop-blur-sm border border-white border-opacity-20">
                <TrendingUpIcon className="h-4 w-4 text-green-600" />
                <span className="text-sm font-semibold text-gray-700">
                  {filteredReports.length} {filteredReports.length === 1 ? 'Report' : 'Reports'}
                </span>
              </div>
              
              <Button 
                variant="primary" 
                onClick={() => navigate('/assessment')}
              >
                <div className="flex items-center space-x-2">
                  <PlusIcon size={18} />
                  <span>{t('New Assessment')}</span>
                </div>
              </Button>
            </div>
          </div>
        </div>
      </div>

      {/* Enhanced Filter and Search Section */}
      <Card className="mb-8 p-6 shadow-xl bg-gradient-to-r from-white to-gray-50 border-0">
        <div className="flex flex-col lg:flex-row lg:items-center lg:justify-between gap-6">
          <div className="relative flex-1 max-w-md">
            <SearchIcon className="absolute left-4 top-1/2 transform -translate-y-1/2 text-gray-400 h-5 w-5" />
            <input
              type="text"
              value={searchTerm}
              onChange={(event) => setSearchTerm(event.target.value)}
              placeholder={t('Search reports by name or location...')}
              className="pl-12 pr-4 py-3 border-2 border-gray-200 rounded-xl w-full focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent bg-white shadow-sm text-gray-700 placeholder-gray-400 transition-all duration-300"
            />
          </div>

          <div className="flex items-center space-x-4">
            <div className="flex items-center space-x-2">
              <FilterIcon className="h-4 w-4 text-gray-500" />
              <select
                value={statusFilter}
                onChange={(event) =>
                  setStatusFilter(event.target.value as StatusFilter)
                }
                className="border-2 border-gray-200 rounded-xl py-3 px-4 bg-white focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent shadow-sm text-gray-700 font-medium transition-all duration-300"
                title="Filter by status"
              >
                <option value="all">{t('All Status')}</option>
                <option value="suitable">{t('Highly Suitable')}</option>
                <option value="conditional">{t('Conditionally Suitable')}</option>
                <option value="unsuitable">{t('Not Recommended')}</option>
              </select>
            </div>

            <div className="flex items-center space-x-2">
              <SortAscIcon className="h-4 w-4 text-gray-500" />
              <select
                value={sortOption}
                onChange={(event) =>
                  setSortOption(event.target.value as SortOption)
                }
                className="border-2 border-gray-200 rounded-xl py-3 px-4 bg-white focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent shadow-sm text-gray-700 font-medium transition-all duration-300"
                title="Sort reports"
              >
                <option value="newest">{t('Newest First')}</option>
                <option value="oldest">{t('Oldest First')}</option>
                <option value="potential">{t('Highest Potential')}</option>
              </select>
            </div>

            <Button
              variant="outline"
              onClick={loadReports}
              disabled={loading}
            >
              <div className="flex items-center space-x-2">
                <RefreshCwIcon size={16} className={loading ? 'animate-spin' : ''} />
                <span className="font-medium">Refresh</span>
              </div>
            </Button>
          </div>
        </div>
      </Card>

      {/* Enhanced Error State */}
      {error && (
        <Card className="mb-8 p-6 border-2 border-red-200 bg-gradient-to-r from-red-50 to-rose-50 shadow-lg">
          <div className="flex items-center justify-between">
            <div className="flex items-center space-x-4">
              <div className="w-12 h-12 bg-red-100 rounded-xl flex items-center justify-center">
                <XCircleIcon className="h-6 w-6 text-red-600" />
              </div>
              <div>
                <p className="text-red-800 font-semibold text-lg">{error}</p>
                <p className="text-red-600 text-sm mt-1">Please check your connection and try again</p>
              </div>
            </div>
            <Button variant="outline" size="sm" onClick={loadReports}>
              <div className="flex items-center space-x-2">
                <RefreshCwIcon size={16} />
                <span>{t('Retry')}</span>
              </div>
            </Button>
          </div>
        </Card>
      )}

      {/* Enhanced Loading State */}
      {loading ? (
        <Card className="p-12 text-center bg-gradient-to-br from-blue-50 to-indigo-50 shadow-xl border-0">
          <div className="flex flex-col items-center space-y-4">
            <div className="w-16 h-16 bg-gradient-to-r from-blue-500 to-indigo-600 rounded-2xl flex items-center justify-center shadow-lg">
              <LoaderIcon className="h-8 w-8 text-white animate-spin" />
            </div>
            <div>
              <p className="text-xl font-semibold text-gray-800 mb-2">{t('Loading reports...')}</p>
              <p className="text-gray-600">Fetching your assessment data</p>
            </div>
          </div>
        </Card>
      ) : (
        /* Enhanced Report Cards */
        <div className="space-y-6">
          {filteredReports.map((report) => (
            <Card
              key={report.id}
              className="p-6 hover:shadow-2xl transition-all duration-300 transform hover:-translate-y-1 bg-gradient-to-r from-white to-gray-50 border-0 shadow-lg"
            >
              <div className="flex flex-col lg:flex-row lg:items-center lg:justify-between gap-6">
                <div className="flex items-start space-x-4">
                  <div className="w-16 h-16 bg-gradient-to-br from-blue-500 to-indigo-600 rounded-2xl flex items-center justify-center shadow-xl flex-shrink-0">
                    <FileTextIcon className="h-8 w-8 text-white" />
                  </div>
                  <div className="flex-1">
                    <h3 className="text-xl font-bold text-gray-800 mb-2">{report.name}</h3>
                    <div className="flex items-center space-x-2 text-gray-600 mb-3">
                      <MapPinIcon size={16} className="text-gray-400" />
                      <span className="text-sm">{report.location || '—'}</span>
                    </div>
                    
                    <div className="flex flex-wrap items-center gap-4">
                      <div className="flex items-center space-x-2">
                        <CalendarIcon size={14} className="text-gray-400" />
                        <span className="text-sm text-gray-600 font-medium">
                          {formatDate(report.date)}
                        </span>
                      </div>
                      
                      {/* Enhanced Status Badge */}
                      <div className="flex items-center space-x-2">
                        {report.status === 'suitable' && <CheckCircleIcon size={14} className="text-green-600" />}
                        {report.status === 'conditional' && <AlertTriangleIcon size={14} className="text-yellow-600" />}
                        {report.status === 'unsuitable' && <XCircleIcon size={14} className="text-red-600" />}
                        {getStatusBadge(report.status)}
                      </div>
                      
                      <div className="flex items-center space-x-2 px-3 py-1 bg-gradient-to-r from-blue-100 to-indigo-100 rounded-full">
                        <TrendingUpIcon size={14} className="text-blue-600" />
                        <span className="text-sm font-bold text-blue-700">
                          {formatHarvestPotential(report.harvestPotential)}
                        </span>
                      </div>
                    </div>
                  </div>
                </div>
                
                {/* Enhanced Action Buttons */}
                <div className="flex items-center space-x-3">
                  <Button
                    variant="outline"
                    size="sm"
                    onClick={() => navigate(`/results?id=${report.id}`)}
                  >
                    <div className="flex items-center space-x-2">
                      <EyeIcon size={16} />
                      <span>{t('View')}</span>
                    </div>
                  </Button>
                  
                  <Button
                    variant="primary"
                    size="sm"
                    onClick={() => downloadReportAsPDF(report)}
                    disabled={downloadingPdf === report.id}
                  >
                    <div className="flex items-center space-x-2">
                      {downloadingPdf === report.id ? (
                        <LoaderIcon size={16} className="animate-spin" />
                      ) : (
                        <DownloadIcon size={16} />
                      )}
                      <span>{downloadingPdf === report.id ? 'Generating...' : t('Download PDF')}</span>
                    </div>
                  </Button>
                </div>
              </div>
            </Card>
          ))}
        </div>
      )}

      {/* Enhanced Empty State */}
      {!loading && !error && filteredReports.length === 0 && (
        <div className="text-center py-20">
          <div className="w-32 h-32 bg-gradient-to-br from-gray-100 to-gray-200 rounded-3xl flex items-center justify-center mx-auto mb-8 shadow-xl">
            <FileTextIcon className="h-16 w-16 text-gray-400" />
          </div>
          <h3 className="text-2xl font-bold text-gray-800 mb-3">
            {reports.length === 0 ? t('No reports yet') : 'No matching reports'}
          </h3>
          <p className="text-gray-600 mb-8 max-w-md mx-auto text-lg">
            {reports.length === 0 
              ? t('Start your first assessment to generate a comprehensive rainwater harvesting report.') 
              : 'Try adjusting your search or filter criteria to find the reports you\'re looking for.'
            }
          </p>
          
          <div className="flex flex-col sm:flex-row items-center justify-center space-y-3 sm:space-y-0 sm:space-x-4">
            <Button variant="primary" onClick={() => navigate('/assessment')}>
              <div className="flex items-center space-x-2">
                <PlusIcon size={18} />
                <span>{reports.length === 0 ? t('Start Assessment') : 'New Assessment'}</span>
              </div>
            </Button>
            
            {reports.length > 0 && (
              <Button 
                variant="outline" 
                onClick={() => {
                  setSearchTerm('');
                  setStatusFilter('all');
                  setSortOption('newest');
                }}
              >
                <div className="flex items-center space-x-2">
                  <RefreshCwIcon size={16} />
                  <span>Clear Filters</span>
                </div>
              </Button>
            )}
          </div>
        </div>
      )}
    </MainLayout>
  );
};

export default Reports;
